/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.voteapp;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.Math;

/**
 *
 * @author Asus
 */
public class App extends javax.swing.JFrame {

	/**
	 * Creates new form App
	 */
	public App() {
		initComponents();
		DatabaseTable.setEnabled(false);
	}

	String CurrentlyChosen = "";
	double AmountOfVotes = 0;
	double EthanVotes = 0;
	double ClaytonVotes = 0;
	double ClaudiusVotes = 0;
	ArrayList <Student> StudentList = new ArrayList();

	public void initAppearance() {
		Object[] title = {"Username", "Password", "NIS", "Full Name", "Class", "Voted"};

		Object[][] StudentData = new Object[StudentList.size()][title.length];

		for (int i = 0; i < StudentList.size(); i++) {
			StudentData[i][0] = StudentList.get(i).getUsername();
			StudentData[i][1] = StudentList.get(i).getPassword();
			StudentData[i][2] = StudentList.get(i).getNIS();
			StudentData[i][3] = StudentList.get(i).getName();
			StudentData[i][4] = StudentList.get(i).getClass_();
			StudentData[i][5] = StudentList.get(i).isVoted();
		}

		DefaultTableModel dtm = new DefaultTableModel(StudentData, title);
		DatabaseTable.setModel(dtm);
		Scroll.setViewportView(DatabaseTable);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                SignUpFrame = new javax.swing.JFrame();
                SignUpTitleLabel = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                CreateAccountButton = new javax.swing.JButton();
                NewUsernameField = new javax.swing.JTextField();
                NewPasswordField = new javax.swing.JPasswordField();
                ConfirmNewPasswordField = new javax.swing.JPasswordField();
                FullNameField = new javax.swing.JTextField();
                NISField = new javax.swing.JTextField();
                LogInRefer = new javax.swing.JButton();
                ClassComboBox = new javax.swing.JComboBox<>();
                jPanel1 = new javax.swing.JPanel();
                jCheckBox1 = new javax.swing.JCheckBox();
                VotingFrame = new javax.swing.JFrame();
                VoteButton = new javax.swing.JButton();
                ConfirmCheckBox = new javax.swing.JCheckBox();
                LogOutButton = new javax.swing.JButton();
                CurrentUserLabel = new javax.swing.JLabel();
                ClaudiusButton = new javax.swing.JButton();
                ClaytonButton = new javax.swing.JButton();
                EthanButton = new javax.swing.JButton();
                DatabaseFrame = new javax.swing.JFrame();
                Scroll = new javax.swing.JScrollPane();
                DatabaseTable = new javax.swing.JTable();
                ReturnButton = new javax.swing.JButton();
                CurrentStandingsLabel = new javax.swing.JLabel();
                EthanStandingsLabel = new javax.swing.JLabel();
                ClaytonStandingsLabel = new javax.swing.JLabel();
                ClaudiusStandingsLabel = new javax.swing.JLabel();
                TotalVotesLabel = new javax.swing.JLabel();
                LogInTitleLabel = new javax.swing.JLabel();
                UsernameLabel = new javax.swing.JLabel();
                UsernameField = new javax.swing.JTextField();
                PasswordLabel = new javax.swing.JLabel();
                PasswordField = new javax.swing.JPasswordField();
                LogInButton = new javax.swing.JButton();
                CreateAccountRefer = new javax.swing.JButton();

                SignUpFrame.setMinimumSize(new java.awt.Dimension(400, 400));
                SignUpFrame.setPreferredSize(new java.awt.Dimension(400, 400));
                SignUpFrame.setResizable(false);

                SignUpTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                SignUpTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                SignUpTitleLabel.setText("Create an Account");

                jLabel1.setText("Username");

                jLabel2.setText("Password");

                jLabel3.setText("Confirm Password");

                jLabel4.setText("Class");

                jLabel5.setText("Full Name");

                jLabel6.setText("NIS");

                CreateAccountButton.setBackground(new java.awt.Color(51, 153, 0));
                CreateAccountButton.setText("Create Account");
                CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CreateAccountButtonActionPerformed(evt);
                        }
                });

                LogInRefer.setBackground(new java.awt.Color(0, 102, 255));
                LogInRefer.setText("Go back to Log In");
                LogInRefer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInReferActionPerformed(evt);
                        }
                });

                ClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7A", "7B", "7C", "8A", "8B", "8C", "9A", "9B", "9C", "10A", "10B", "10C", "11A", "11B", "11C", "12A", "12B", "12C" }));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                jCheckBox1.setText("I will choose honestly and without bias.");

                javax.swing.GroupLayout SignUpFrameLayout = new javax.swing.GroupLayout(SignUpFrame.getContentPane());
                SignUpFrame.getContentPane().setLayout(SignUpFrameLayout);
                SignUpFrameLayout.setHorizontalGroup(
                        SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SignUpTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(LogInRefer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpFrameLayout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(ConfirmNewPasswordField))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpFrameLayout.createSequentialGroup()
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2))
                                                                .addGap(54, 54, 54)
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(NewPasswordField)
                                                                        .addComponent(NewUsernameField)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpFrameLayout.createSequentialGroup()
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(53, 53, 53)
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(FullNameField)
                                                                        .addComponent(NISField)
                                                                        .addComponent(ClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                                        .addComponent(CreateAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                SignUpFrameLayout.setVerticalGroup(
                        SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SignUpTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(NewUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(ConfirmNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(ClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(FullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(NISField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAccountButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LogInRefer)
                                .addContainerGap(88, Short.MAX_VALUE))
                );

                VotingFrame.setMinimumSize(new java.awt.Dimension(500, 500));
                VotingFrame.setPreferredSize(new java.awt.Dimension(500, 500));

                VoteButton.setBackground(new java.awt.Color(0, 204, 102));
                VoteButton.setText("Vote");
                VoteButton.setEnabled(false);
                VoteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                VoteButtonActionPerformed(evt);
                        }
                });

                ConfirmCheckBox.setText("I confirm my choice");
                ConfirmCheckBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ConfirmCheckBoxActionPerformed(evt);
                        }
                });

                LogOutButton.setBackground(new java.awt.Color(255, 51, 51));
                LogOutButton.setText("Log Out");
                LogOutButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogOutButtonActionPerformed(evt);
                        }
                });

                CurrentUserLabel.setForeground(new java.awt.Color(102, 102, 102));
                CurrentUserLabel.setText("Signed in as: ");
                CurrentUserLabel.setMaximumSize(new java.awt.Dimension(255, 357));
                CurrentUserLabel.setMinimumSize(new java.awt.Dimension(255, 357));
                CurrentUserLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                        public void propertyChange(java.beans.PropertyChangeEvent evt) {
                                CurrentUserLabelPropertyChange(evt);
                        }
                });

                ClaudiusButton.setText("Claudius");
                ClaudiusButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ClaudiusButtonActionPerformed(evt);
                        }
                });

                ClaytonButton.setText("Clayton");
                ClaytonButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ClaytonButtonActionPerformed(evt);
                        }
                });

                EthanButton.setText("Ethan");
                EthanButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EthanButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout VotingFrameLayout = new javax.swing.GroupLayout(VotingFrame.getContentPane());
                VotingFrame.getContentPane().setLayout(VotingFrameLayout);
                VotingFrameLayout.setHorizontalGroup(
                        VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VotingFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(VotingFrameLayout.createSequentialGroup()
                                                .addComponent(CurrentUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                                .addGap(84, 84, 84))
                                        .addGroup(VotingFrameLayout.createSequentialGroup()
                                                .addGroup(VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(LogOutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(VoteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(ConfirmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(VotingFrameLayout.createSequentialGroup()
                                                                        .addComponent(EthanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(ClaytonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(ClaudiusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                VotingFrameLayout.setVerticalGroup(
                        VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VotingFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                        .addComponent(EthanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ClaytonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ClaudiusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConfirmCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VoteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LogOutButton)
                                .addGap(32, 32, 32)
                                .addComponent(CurrentUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(124, Short.MAX_VALUE))
                );

                DatabaseFrame.setMinimumSize(new java.awt.Dimension(500, 500));
                DatabaseFrame.setPreferredSize(new java.awt.Dimension(500, 500));

                DatabaseTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                Scroll.setViewportView(DatabaseTable);

                ReturnButton.setBackground(new java.awt.Color(255, 51, 51));
                ReturnButton.setText("Return");
                ReturnButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReturnButtonActionPerformed(evt);
                        }
                });

                CurrentStandingsLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
                CurrentStandingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                CurrentStandingsLabel.setText("Current Standings");

                EthanStandingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                EthanStandingsLabel.setText("Ethan: ");

                ClaytonStandingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                ClaytonStandingsLabel.setText("Clayton: ");

                ClaudiusStandingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                ClaudiusStandingsLabel.setText("Claudius:");

                TotalVotesLabel.setText("jLabel7");

                javax.swing.GroupLayout DatabaseFrameLayout = new javax.swing.GroupLayout(DatabaseFrame.getContentPane());
                DatabaseFrame.getContentPane().setLayout(DatabaseFrameLayout);
                DatabaseFrameLayout.setHorizontalGroup(
                        DatabaseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatabaseFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DatabaseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                                        .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CurrentStandingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EthanStandingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClaytonStandingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClaudiusStandingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TotalVotesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                DatabaseFrameLayout.setVerticalGroup(
                        DatabaseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatabaseFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReturnButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CurrentStandingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EthanStandingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClaytonStandingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClaudiusStandingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TotalVotesLabel)
                                .addContainerGap(7, Short.MAX_VALUE))
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                setResizable(false);

                LogInTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                LogInTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                LogInTitleLabel.setText("CBCS Stucon President Vote App");

                UsernameLabel.setText("Username");

                PasswordLabel.setText("Password");

                LogInButton.setBackground(new java.awt.Color(0, 102, 255));
                LogInButton.setText("Log In");
                LogInButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInButtonActionPerformed(evt);
                        }
                });

                CreateAccountRefer.setBackground(new java.awt.Color(51, 153, 0));
                CreateAccountRefer.setText("Create Account");
                CreateAccountRefer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CreateAccountReferActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LogInTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CreateAccountRefer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(UsernameLabel)
                                                        .addComponent(PasswordLabel)
                                                        .addComponent(UsernameField)
                                                        .addComponent(PasswordField)
                                                        .addComponent(LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LogInTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(LogInButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAccountRefer)
                                .addContainerGap(63, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void CreateAccountReferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountReferActionPerformed
                // TODO add your handling code here:
		SignUpFrame.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_CreateAccountReferActionPerformed

        private void LogInReferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInReferActionPerformed
                // TODO add your handling code here:
		this.setVisible(true);
		SignUpFrame.setVisible(false);
        }//GEN-LAST:event_LogInReferActionPerformed

        private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
                // TODO add your handling code here:
		boolean goodtogo = true;
		if (
			!(NewUsernameField.getText().equals("")) &&
			!(NewPasswordField.getText().equals("")) &&
			!(ConfirmNewPasswordField.getText().equals("")) &&
			!(FullNameField.getText().equals("")) &&
			!(NISField.getText().equals(""))
			) {
			for (int i = 0; i < StudentList.size(); i++) {
				if (
					NewUsernameField.getText().equals(StudentList.get(i).getUsername()) ||
					NISField.getText().equals(StudentList.get(i).getNIS())
					) {
					goodtogo = false;
				}
			}
			if (goodtogo == true) {
				if (NewPasswordField.getText().equals(ConfirmNewPasswordField.getText())) {
					StudentList.add(new Student(
						NewUsernameField.getText(),
						NewPasswordField.getText(),
						NISField.getText(),
						FullNameField.getText(),
						ClassComboBox.getSelectedItem().toString(),
						false
					));
					JOptionPane.showMessageDialog(null, "Registered successfully!");
					SignUpFrame.setVisible(false);
					this.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(null, "Your passwords don't match.");
				}
			} else {
				JOptionPane.showMessageDialog(null, "Username/NIS already exists in the database. Contact a developer to help you vote instead.");
			}
		} else {
			JOptionPane.showMessageDialog(null, "You've left some of the fields empty.");
		}	
        }//GEN-LAST:event_CreateAccountButtonActionPerformed

        private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
                // TODO add your handling code here:
		boolean showerror = true;
		for (int i = 0; i < StudentList.size(); i++) {
			if (
				UsernameField.getText().equals(StudentList.get(i).getUsername()) &&
				PasswordField.getText().equals(StudentList.get(i).getPassword())
				) {
				this.setVisible(false);
				VotingFrame.setVisible(true);
				CurrentUserLabel.setText("Signed in as: " + UsernameField.getText());
				if (StudentList.get(i).isVoted() == true) {
					VoteButton.setEnabled(false);
					ConfirmCheckBox.setEnabled(false);
				} else {
					VoteButton.setEnabled(false);
					ConfirmCheckBox.setEnabled(true);
					ConfirmCheckBox.setSelected(false);
				}
				showerror = false;
			}
		}
		if (
			UsernameField.getText().equals("admin") &&
			PasswordField.getText().equals("admin")

			) {
			this.setVisible(false);
			DatabaseFrame.setVisible(true);

			EthanStandingsLabel.setText("Ethan: " + String.valueOf((EthanVotes/AmountOfVotes)*100) + "%");
			ClaytonStandingsLabel.setText("Clayton: " + String.valueOf((ClaytonVotes/AmountOfVotes)*100) + "%");
			ClaudiusStandingsLabel.setText("Claudius: " + String.valueOf((ClaudiusVotes/AmountOfVotes)*100) + "%");
			TotalVotesLabel.setText("Total Votes: " + String.valueOf((int)AmountOfVotes));

			showerror = false;
		}
		if (showerror == true) {
			JOptionPane.showMessageDialog(null, "Invalid username and password pair.");
		}
		initAppearance();
        }//GEN-LAST:event_LogInButtonActionPerformed

        private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
                // TODO add your handling code here:
		this.setVisible(true);
		DatabaseFrame.setVisible(false);
        }//GEN-LAST:event_ReturnButtonActionPerformed

        private void ConfirmCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmCheckBoxActionPerformed
                // TODO add your handling code here:
		if (ConfirmCheckBox.isSelected()) {
			VoteButton.setEnabled(true);
		} else {
			VoteButton.setEnabled(false);
		}
        }//GEN-LAST:event_ConfirmCheckBoxActionPerformed

        private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
                // TODO add your handling code here:
		VotingFrame.setVisible(false);
		this.setVisible(true);
        }//GEN-LAST:event_LogOutButtonActionPerformed

        private void CurrentUserLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CurrentUserLabelPropertyChange
                // TODO add your handling code here:
        }//GEN-LAST:event_CurrentUserLabelPropertyChange

        private void VoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteButtonActionPerformed
                // TODO add your handling code here:
		if (!(CurrentlyChosen.equals(""))) {
			for (int i = 0; i < StudentList.size(); i++) {
				if (UsernameField.getText().equals(StudentList.get(i).getUsername())) {
					StudentList.get(i).setVoted(true);
				}
			}
			AmountOfVotes += 1;
			if (CurrentlyChosen.equals("Ethan")) {
				EthanVotes += 1;
			} else if (CurrentlyChosen.equals("Clayton")) {
				ClaytonVotes += 1;
			} else if (CurrentlyChosen.equals("Claudius")) {
				ClaudiusVotes += 1;
			}
			JOptionPane.showMessageDialog(null, "You've successfully voted!");
			for (int i = 0; i < StudentList.size(); i++) {
				if (UsernameField.getText().equals(StudentList.get(i).getUsername())) {
					if (StudentList.get(i).isVoted() == true) {
						VoteButton.setEnabled(false);
						ConfirmCheckBox.setEnabled(false);
					}
				}
			}
		} else {
			JOptionPane.showMessageDialog(null,"Choose somebody.");
		}

        }//GEN-LAST:event_VoteButtonActionPerformed

        private void ClaudiusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaudiusButtonActionPerformed
                // TODO add your handling code here:
                EthanButton.setBackground(Color.GRAY);
                ClaytonButton.setBackground(Color.GRAY);
                ClaudiusButton.setBackground(Color.GREEN);
		CurrentlyChosen = "Claudius";
        }//GEN-LAST:event_ClaudiusButtonActionPerformed

        private void ClaytonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaytonButtonActionPerformed
                // TODO add your handling code here:
                EthanButton.setBackground(Color.GRAY);
                ClaytonButton.setBackground(Color.GREEN);
                ClaudiusButton.setBackground(Color.GRAY);
		CurrentlyChosen = "Clayton";
        }//GEN-LAST:event_ClaytonButtonActionPerformed

        private void EthanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EthanButtonActionPerformed
                // TODO add your handling code here:
                EthanButton.setBackground(Color.GREEN);
                ClaytonButton.setBackground(Color.GRAY);
                ClaudiusButton.setBackground(Color.GRAY);
		CurrentlyChosen = "Ethan";
        }//GEN-LAST:event_EthanButtonActionPerformed


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new App().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> ClassComboBox;
        private javax.swing.JButton ClaudiusButton;
        private javax.swing.JLabel ClaudiusStandingsLabel;
        private javax.swing.JButton ClaytonButton;
        private javax.swing.JLabel ClaytonStandingsLabel;
        private javax.swing.JCheckBox ConfirmCheckBox;
        private javax.swing.JPasswordField ConfirmNewPasswordField;
        private javax.swing.JButton CreateAccountButton;
        private javax.swing.JButton CreateAccountRefer;
        private javax.swing.JLabel CurrentStandingsLabel;
        private javax.swing.JLabel CurrentUserLabel;
        private javax.swing.JFrame DatabaseFrame;
        private javax.swing.JTable DatabaseTable;
        private javax.swing.JButton EthanButton;
        private javax.swing.JLabel EthanStandingsLabel;
        private javax.swing.JTextField FullNameField;
        private javax.swing.JButton LogInButton;
        private javax.swing.JButton LogInRefer;
        private javax.swing.JLabel LogInTitleLabel;
        private javax.swing.JButton LogOutButton;
        private javax.swing.JTextField NISField;
        private javax.swing.JPasswordField NewPasswordField;
        private javax.swing.JTextField NewUsernameField;
        private javax.swing.JPasswordField PasswordField;
        private javax.swing.JLabel PasswordLabel;
        private javax.swing.JButton ReturnButton;
        private javax.swing.JScrollPane Scroll;
        private javax.swing.JFrame SignUpFrame;
        private javax.swing.JLabel SignUpTitleLabel;
        private javax.swing.JLabel TotalVotesLabel;
        private javax.swing.JTextField UsernameField;
        private javax.swing.JLabel UsernameLabel;
        private javax.swing.JButton VoteButton;
        private javax.swing.JFrame VotingFrame;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        // End of variables declaration//GEN-END:variables
}
