/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.voteapp;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class App extends javax.swing.JFrame {

	/**
	 * Creates new form App
	 */
	public App() {
		initComponents();
		initAppearance();
		DatabaseTable.setEnabled(false);
		
	}

	ArrayList <Student> StudentList = new ArrayList();

	public void initAppearance() {
		Object[] title = {"Username", "Password", "NIS", "Full Name", "Class", "Voted"};

		Object[][] StudentData = new Object[StudentList.size()][title.length];

		for (int i = 0; i < StudentList.size(); i++) {
			StudentData[i][0] = StudentList.get(i).getUsername();
			StudentData[i][1] = StudentList.get(i).getPassword();
			StudentData[i][2] = StudentList.get(i).getNIS();
			StudentData[i][3] = StudentList.get(i).getName();
			StudentData[i][4] = StudentList.get(i).getClass();
			StudentData[i][5] = StudentList.get(i).isVoted();
		}

		DefaultTableModel dtm = new DefaultTableModel(StudentData, title);
		DatabaseTable.setModel(dtm);
		Scroll.setViewportView(DatabaseTable);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                SignUpFrame = new javax.swing.JFrame();
                SignUpTitleLabel = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                CreateAccountButton = new javax.swing.JButton();
                NewUsernameField = new javax.swing.JTextField();
                NewPasswordField = new javax.swing.JPasswordField();
                ConfirmNewPasswordField = new javax.swing.JPasswordField();
                FullNameField = new javax.swing.JTextField();
                NISField = new javax.swing.JTextField();
                LogInRefer = new javax.swing.JButton();
                ClassComboBox = new javax.swing.JComboBox<>();
                jPanel1 = new javax.swing.JPanel();
                jCheckBox1 = new javax.swing.JCheckBox();
                VotingFrame = new javax.swing.JFrame();
                jPanel2 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                DatabaseFrame = new javax.swing.JFrame();
                Scroll = new javax.swing.JScrollPane();
                DatabaseTable = new javax.swing.JTable();
                LogInTitleLabel = new javax.swing.JLabel();
                UsernameLabel = new javax.swing.JLabel();
                UsernameField = new javax.swing.JTextField();
                PasswordLabel = new javax.swing.JLabel();
                PasswordField = new javax.swing.JPasswordField();
                LogInButton = new javax.swing.JButton();
                CreateAccountRefer = new javax.swing.JButton();

                SignUpFrame.setMinimumSize(new java.awt.Dimension(400, 400));
                SignUpFrame.setResizable(false);

                SignUpTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                SignUpTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                SignUpTitleLabel.setText("Create an Account");

                jLabel1.setText("Username");

                jLabel2.setText("Password");

                jLabel3.setText("Confirm Password");

                jLabel4.setText("Class");

                jLabel5.setText("Full Name");

                jLabel6.setText("NIS");

                CreateAccountButton.setBackground(new java.awt.Color(51, 153, 0));
                CreateAccountButton.setText("Create Account");
                CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CreateAccountButtonActionPerformed(evt);
                        }
                });

                LogInRefer.setBackground(new java.awt.Color(0, 102, 255));
                LogInRefer.setText("Go back to Log In");
                LogInRefer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInReferActionPerformed(evt);
                        }
                });

                ClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7A", "7B", "7C", "8A", "8B", "8C", "9A", "9B", "9C", "10A", "10B", "10C", "11A", "11B", "11C", "12A", "12B", "12C" }));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                jCheckBox1.setText("I will choose honestly and without bias.");

                javax.swing.GroupLayout SignUpFrameLayout = new javax.swing.GroupLayout(SignUpFrame.getContentPane());
                SignUpFrame.getContentPane().setLayout(SignUpFrameLayout);
                SignUpFrameLayout.setHorizontalGroup(
                        SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SignUpTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(LogInRefer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpFrameLayout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(ConfirmNewPasswordField))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpFrameLayout.createSequentialGroup()
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2))
                                                                .addGap(54, 54, 54)
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(NewPasswordField)
                                                                        .addComponent(NewUsernameField)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpFrameLayout.createSequentialGroup()
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(53, 53, 53)
                                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(FullNameField)
                                                                        .addComponent(NISField)
                                                                        .addComponent(ClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                                        .addComponent(CreateAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                SignUpFrameLayout.setVerticalGroup(
                        SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SignUpTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(NewUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(ConfirmNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(ClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(FullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(SignUpFrameLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(NISField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAccountButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LogInRefer)
                                .addContainerGap(88, Short.MAX_VALUE))
                );

                VotingFrame.setMinimumSize(new java.awt.Dimension(400, 400));
                VotingFrame.setPreferredSize(new java.awt.Dimension(400, 400));
                VotingFrame.setResizable(false);

                jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                jButton1.setText("Ethan");

                jButton2.setText("Clayton");

                jButton3.setText("Claudius");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout VotingFrameLayout = new javax.swing.GroupLayout(VotingFrame.getContentPane());
                VotingFrame.getContentPane().setLayout(VotingFrameLayout);
                VotingFrameLayout.setHorizontalGroup(
                        VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VotingFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                VotingFrameLayout.setVerticalGroup(
                        VotingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VotingFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(70, Short.MAX_VALUE))
                );

                DatabaseFrame.setMinimumSize(new java.awt.Dimension(500, 500));
                DatabaseFrame.setPreferredSize(new java.awt.Dimension(500, 500));

                DatabaseTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                Scroll.setViewportView(DatabaseTable);

                javax.swing.GroupLayout DatabaseFrameLayout = new javax.swing.GroupLayout(DatabaseFrame.getContentPane());
                DatabaseFrame.getContentPane().setLayout(DatabaseFrameLayout);
                DatabaseFrameLayout.setHorizontalGroup(
                        DatabaseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatabaseFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addContainerGap())
                );
                DatabaseFrameLayout.setVerticalGroup(
                        DatabaseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DatabaseFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                .addContainerGap())
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                setResizable(false);

                LogInTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                LogInTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                LogInTitleLabel.setText("CBCS Stucon President Vote App");

                UsernameLabel.setText("Username");

                PasswordLabel.setText("Password");

                LogInButton.setBackground(new java.awt.Color(0, 102, 255));
                LogInButton.setText("Log In");
                LogInButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogInButtonActionPerformed(evt);
                        }
                });

                CreateAccountRefer.setBackground(new java.awt.Color(51, 153, 0));
                CreateAccountRefer.setText("Create Account");
                CreateAccountRefer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CreateAccountReferActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LogInTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CreateAccountRefer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(UsernameLabel)
                                                        .addComponent(PasswordLabel)
                                                        .addComponent(UsernameField)
                                                        .addComponent(PasswordField)
                                                        .addComponent(LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LogInTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(LogInButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAccountRefer)
                                .addContainerGap(63, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void CreateAccountReferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountReferActionPerformed
                // TODO add your handling code here:
		SignUpFrame.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_CreateAccountReferActionPerformed

        private void LogInReferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInReferActionPerformed
                // TODO add your handling code here:
		this.setVisible(true);
		SignUpFrame.setVisible(false);
        }//GEN-LAST:event_LogInReferActionPerformed

        private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
                // TODO add your handling code here:
		boolean goodtogo = true;
		if (
			!(NewUsernameField.getText().equals("")) &&
			!(NewPasswordField.getText().equals("")) &&
			!(ConfirmNewPasswordField.getText().equals("")) &&
			!(FullNameField.getText().equals("")) &&
			!(NISField.getText().equals(""))
			) {
			for (int i = 0; i < StudentList.size(); i++) {
				if (
					NewUsernameField.getText().equals(StudentList.get(i).getUsername()) ||
					NISField.getText().equals(StudentList.get(i).getNIS())
					) {
					goodtogo = false;
				}
			}
			if (goodtogo == true) {
				if (NewPasswordField.getText().equals(ConfirmNewPasswordField.getText())) {
					StudentList.add(new Student(
						NewUsernameField.getText(),
						NewPasswordField.getText(),
						NISField.getText(),
						FullNameField.getText(),
						String.valueOf(ClassComboBox.getSelectedItem()),
						false
					));
					JOptionPane.showMessageDialog(null, "Registered successfully!");
				} else {
					JOptionPane.showMessageDialog(null, "Your passwords don't match.");
				}
			} else {
				JOptionPane.showMessageDialog(null, "Username/NIS already exists in the database. Contact a developer to help you vote instead.");
			}
		} else {
			JOptionPane.showMessageDialog(null, "You've left some of the fields empty.");
		}	
        }//GEN-LAST:event_CreateAccountButtonActionPerformed

        private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
                // TODO add your handling code here:
		boolean showerror = true;
		for (int i = 0; i < StudentList.size(); i++) {
			if (
				UsernameField.getText().equals(StudentList.get(i).getUsername()) &&
				PasswordField.getText().equals(StudentList.get(i).getPassword())
				) {
				this.setVisible(false);
				VotingFrame.setVisible(true);
				showerror = false;
			}
		}
		if (
			UsernameField.getText().equals("admin") &&
			PasswordField.getText().equals("admin")

			) {
			this.setVisible(false);
			DatabaseFrame.setVisible(true);
			showerror = false;
		}
		if (showerror == true) {
			JOptionPane.showMessageDialog(null, "Invalid username and password pair.");
		}
		initAppearance();
        }//GEN-LAST:event_LogInButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new App().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> ClassComboBox;
        private javax.swing.JPasswordField ConfirmNewPasswordField;
        private javax.swing.JButton CreateAccountButton;
        private javax.swing.JButton CreateAccountRefer;
        private javax.swing.JFrame DatabaseFrame;
        private javax.swing.JTable DatabaseTable;
        private javax.swing.JTextField FullNameField;
        private javax.swing.JButton LogInButton;
        private javax.swing.JButton LogInRefer;
        private javax.swing.JLabel LogInTitleLabel;
        private javax.swing.JTextField NISField;
        private javax.swing.JPasswordField NewPasswordField;
        private javax.swing.JTextField NewUsernameField;
        private javax.swing.JPasswordField PasswordField;
        private javax.swing.JLabel PasswordLabel;
        private javax.swing.JScrollPane Scroll;
        private javax.swing.JFrame SignUpFrame;
        private javax.swing.JLabel SignUpTitleLabel;
        private javax.swing.JTextField UsernameField;
        private javax.swing.JLabel UsernameLabel;
        private javax.swing.JFrame VotingFrame;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        // End of variables declaration//GEN-END:variables
}
